Parallel multiplication
alexander-kurdakov/Programming_2Year pull request #2
Opened 2021-11-18 00:58 UTC by alexander-kurdakov

Mini report, tests.

2021-11-21 10:32 UTC, yurii-litvinov requested changes

2021-11-21 10:32 UTC, yurii-litvinov commented on src/ParallelMultiplication/ParallelMultiplication.Tests/ParallelMultiplication.Tests.csproj
> +        <TargetFramework>net5.0</TargetFramework>
.NET 5 --- это какая-то legacy-технология, все давно на .NET 6 перешли

2021-11-21 10:32 UTC, yurii-litvinov commented on src/ParallelMultiplication/ParallelMultiplication.Tests/UnitTests.cs
> +        }
Не, один тест должен проверять один тестовый сценарий, чтобы если тест не прошёл, сразу было понятно, что сломалось. Надо разбить этот тест на несколько.

2021-11-21 10:32 UTC, yurii-litvinov commented on src/ParallelMultiplication/ParallelMultiplication/FileWorker.cs
> +    public class FileWorker
```suggestion
    public static class FileWorker
```
Иначе кто-нибудь будет создавать объекты этого класса или ещё что-то такое

2021-11-21 10:32 UTC, yurii-litvinov commented on src/ParallelMultiplication/ParallelMultiplication/FileWorker.cs
> +        public static void Print(string path, long[,] arr)
![image](https://user-images.githubusercontent.com/706768/142758170-27408d57-f9a7-4438-ae3b-06e3a4146dda.png)
Никогда не сокращайте имена идентификаторов.

2021-11-21 10:32 UTC, yurii-litvinov commented on src/ParallelMultiplication/ParallelMultiplication/FileWorker.cs
> +                    text = text + arr[i, j] + " ";
Используйте StringBuilder для конкатенации строк внутри циклов

2021-11-21 10:32 UTC, yurii-litvinov commented on src/ParallelMultiplication/ParallelMultiplication/FileWorker.cs
> +                var splited = lines[i].Split(' ');
splitted

2021-11-21 10:32 UTC, yurii-litvinov commented on src/ParallelMultiplication/ParallelMultiplication/Multiplication.cs
> +             var threads = new Thread[Environment.ProcessorCount];
Если матрицы по размеру меньше, чем Environment.ProcessorCount, создадутся лишние потоки. Стоит брать минимум из Environment.ProcessorCount и измерений матриц

2021-11-21 10:32 UTC, yurii-litvinov commented on src/ParallelMultiplication/ParallelMultiplication/Multiplication.cs
> +             for (var i = 0; i < threads.Length; i++) {
```suggestion
             for (var i = 0; i < threads.Length; i++) 
             {
```

2021-11-21 10:32 UTC, yurii-litvinov commented on src/ParallelMultiplication/ParallelMultiplication/Program.cs
> +            static void Perfomance(int iterations, int size)
Что-то тут с отступом не то

2021-11-21 10:32 UTC, yurii-litvinov commented on src/ParallelMultiplication/ParallelMultiplication/Multiplication.cs
> +namespace ParallelMultiplication
Кстати, если перейдёте на .NET 6, можно перейти и на file-scoped namespaces, чтобы лишних фигурных скобок не было.

2021-11-21 10:32 UTC, yurii-litvinov commented on src/ParallelMultiplication/ParallelMultiplication/Multiplication.cs
> +         public static long[,] Sequential(long[,] fst, long[,] snd)
Почти всё делается в статических методах, это известный антипаттерн "Функциональная декомпозиция". Подумайте, как перераспределить функциональность так, чтобы получилась более объектно-ориентированная программа (в частности, разные виды умножения делают суть одно и то же, так что я бы это в духе паттерна "Стратегия" сделал).

2021-11-21 15:22 UTC, alexander-kurdakov commented on src/ParallelMultiplication/ParallelMultiplication/Program.cs
> +            static void Perfomance(int iterations, int size)
странно, что райдер этого не замечает =(

2021-11-29 16:28 UTC, alexander-kurdakov commented on src/ParallelMultiplication/ParallelMultiplication.Tests/UnitTests.cs
> +        }
Ок.

2021-12-01 15:00 UTC, yurii-litvinov requested changes

2021-12-07 11:44 UTC, yurii-litvinov approved these changes
В целом всё правильно, зачтена.

2021-12-07 11:44 UTC, yurii-litvinov commented on src/ParallelMultiplication/ParallelMultiplication/Multiplication.cs
> +public class Matrix
Файл должен называться как класс в нём

2021-12-07 11:44 UTC, yurii-litvinov commented on src/ParallelMultiplication/ParallelMultiplication/Multiplication.cs
> +/// Matrix realisation and function to work with it
Лучше "implementation". "realisation" --- это больше "осознание"

2021-12-07 11:44 UTC, yurii-litvinov commented on src/ParallelMultiplication/ParallelMultiplication/Multiplication.cs
> +    public Matrix Multiply(Matrix second, IMatrixMultiplication strategy)
Передавать стратегию всегда может быть неудобно. Её можно принимать в конструктор, или даже принимать необязательным аргументом и иметь тут стратегию по умолчанию. Но это совсем архитектурное соображение, можно не править.

2021-12-07 11:44 UTC, yurii-litvinov commented on src/ParallelMultiplication/ParallelMultiplication/Program.cs
> +            throw new ArgumentOutOfRangeException("wrong number of input strings");
Выкидывать из Main исключения --- не лучший способ сообщить об ошибке в аргументах. Его же ловить некому. Тут хотя бы Console.WriteLine, а лучше развёрнутую подсказку по использованию

2021-12-07 11:44 UTC, yurii-litvinov commented on src/ParallelMultiplication/ParallelMultiplication/SequentialMatrixMultiplication.cs
> +                                        $"second lines: {second.RowNumber}");
Кстати, лучше не выравнивать аргументы по скобке, а использовать стандартный отступ в четыре пробела. Иначе при рефакторинге либо всё поедет, либо придётся равнять по всей программе, что не вариант.

2021-12-10 00:34 UTC, merged